#!/usr/bin/env bash

LANGEAR_SERVER_USER="${LANGEAR_SERVER_USER:-langear-deploy}"
LANGEAR_SERVER_HOST="${LANGEAR_SERVER_HOST:-175.24.204.252}"
LANGEAR_SERVER_DIR="${LANGEAR_SERVER_DIR:-/srv/langear}"
LANGEAR_SERVER_DATA_DIR="${LANGEAR_SERVER_DATA_DIR:-${LANGEAR_SERVER_DIR}/data}"
LANGEAR_SERVER_BACKUP_DIR="${LANGEAR_SERVER_BACKUP_DIR:-${LANGEAR_SERVER_DIR}/backups}"
LANGEAR_SERVER_URL="${LANGEAR_SERVER_URL:-http://${LANGEAR_SERVER_HOST}:8000}"
LANGEAR_REMOTE="${LANGEAR_SERVER_USER}@${LANGEAR_SERVER_HOST}"
LANGEAR_BOOTSTRAP_USER="${LANGEAR_BOOTSTRAP_USER:-ubuntu}"
LANGEAR_BOOTSTRAP_REMOTE="${LANGEAR_BOOTSTRAP_USER}@${LANGEAR_SERVER_HOST}"

server_compose_args() {
  printf "%s" "-f docker-compose.yml -f docker-compose.server.yml"
}
